include <../StandingNotice.scad>

HEIGHT = 300;
WIDTH = 130;
THICKNESS = DEFAULT_THICKNESS;
ANGLE = DEFAULT_ANGLE;
CORNER_RADIUS = DEFAULT_CORNER_RADIUS;

StandingNotice2D(HEIGHT, WIDTH, THICKNESS, ANGLE, CORNER_RADIUS);
