include <../StandingNotice.scad>

HEIGHT = 297; // Height of A4 page
WIDTH = 210; // Width of A4 page
THICKNESS = DEFAULT_THICKNESS;
ANGLE = DEFAULT_ANGLE;
CORNER_RADIUS = DEFAULT_CORNER_RADIUS;

StandingNotice2D(HEIGHT, WIDTH, THICKNESS, ANGLE, CORNER_RADIUS);
