include <../StandingNotice.scad>

WIDTH = 130;
HEIGHT = 300;
THICKNESS = DEFAULT_THICKNESS;
ANGLE = DEFAULT_ANGLE;
CORNER_RADIUS = DEFAULT_CORNER_RADIUS;

StandingNotice2D(WIDTH, HEIGHT, THICKNESS, ANGLE, CORNER_RADIUS);
