include <../StandingNotice.scad>

WIDTH = 210; // Width of A4 page
HEIGHT = 297; // Height of A4 page
THICKNESS = DEFAULT_THICKNESS;
ANGLE = DEFAULT_ANGLE;
CORNER_RADIUS = DEFAULT_CORNER_RADIUS;

StandingNotice2D(WIDTH, HEIGHT, THICKNESS, ANGLE, CORNER_RADIUS);
